version: '3'
services:
  mssql:
    image: "microsoft/mssql-server-linux:2017-latest"
    #build: mssql/.
    container_name: mssql
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=SU2Orange!"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
      - C:/:/root
  cloudera:
    image: "cloudera/quickstart:latest"
    container_name: cloudera
    hostname: quickstart.cloudera
    privileged: true
    stdin_open: true
    tty: true
    ports:
      - "8888:8888" #Hue
      - "7180:7180" # Cloudera Manager
      - "8080:80" #Tutotial
    entrypoint: /usr/bin/docker-quickstart
    volumes:
      - cloudera-data:/var/lib
      - C:/:/root
volumes:
  mssql-data:
  cloudera-data: